version: "3"
services:
  react_native:
    build: ./docker/react_native
    stdin_open: true
    tty: true
    volumes:
      - ./react_native/:/usr/src/app
    env_file: .env
    # command: yarn start
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"